tweak git hook for mac os compat

diff --git a/actions/git-hooks/pre-push b/actions/git-hooks/pre-push
--- a/actions/git-hooks/pre-push
+++ b/actions/git-hooks/pre-push
@@ -8,12 +8,12 @@ DIR=$(pwd)
 PREFIX="[pre-push]"
 
 function cleanup() {
-  # kill all child processes
-  pkill -P $$
+	# kill all child processes
+	pkill -P $$
 }
 # cleanup on exit
 for sig in INT QUIT HUP TERM; do
-  trap "
+	trap "
 	cleanup
 	trap - $sig EXIT
 	kill -s $sig "'"$$"' "$sig"
@@ -32,18 +32,18 @@ echo "$PREFIX Checking docker-compose..."
 cd artifacts || exit
 
 if [ -w "$(which docker-compose)" ]; then
-  DC="docker-compose ps"
+	DC="docker-compose ps"
 else
-  DC="sudo docker-compose ps"
+	DC="sudo docker-compose ps"
 fi
 
 CONTAINERS=('hydra_1' 'hydra_db_1' 'hydra_migrate' 'mongo-express' 'mongo_1' 'redis')
 
 for c in "${CONTAINERS[@]}"; do
-  if ! (eval "$DC" | grep -q "$c" &>/dev/null); then
-    echo "$PREFIX Please ensure docker-compose is up and running."
-    exit 1
-  fi
+	if ! (eval "$DC" | grep -q "$c" &>/dev/null); then
+		echo "$PREFIX Please ensure docker-compose is up and running."
+		exit 1
+	fi
 done
 
 echo "$PREFIX All containers are up and running!"
@@ -56,14 +56,14 @@ echo "$PREFIX All containers are up and running!"
 #
 echo "$PREFIX Starting webapp..."
 
-serverIsRunning() {
-  netstat -tln | grep -q ":9000" &>/dev/null
-  return $?
+serverIsRunning() { 
+	lsof -PiTCP -sTCP:LISTEN | grep -q ":9000" &>/dev/null
+	return $?
 }
 
 if serverIsRunning; then
-  echo "$PREFIX Server already running, please stop it first."
-  exit 1
+	echo "$PREFIX Server already running, please stop it first."
+	exit 1
 fi
 
 cd "$DIR/api" || exit
@@ -71,14 +71,14 @@ make serve &>/dev/null &
 
 n=0
 until [ "$n" -ge 5 ]; do
-  serverIsRunning && break
-  n=$((n + 1))
-  sleep 10
+	serverIsRunning && break
+	n=$((n + 1))
+	sleep 10
 done
 
 if ! serverIsRunning; then
-  echo >&2 "$PREFIX Unable to start webapp."
-  exit 1
+	echo >&2 "$PREFIX Unable to start webapp."
+	exit 1
 fi
 
 echo "$PREFIX Webapp is up and running!"
@@ -88,14 +88,14 @@ cd "$DIR/e2e" || exit
 #
 echo "$PREFIX Running eslint on .js files..."
 if ! npm run lint:fix; then
-  echo >&2 "[pre-push] Linting failed, see output above."
-  exit 1
+	echo >&2 "[pre-push] Linting failed, see output above."
+	exit 1
 fi
 
 echo "$PREFIX Running E2E tests..."
 if ! npm run run; then
-  echo >&2 "[pre-push] E2E tests failed, see output above."
-  exit 1
+	echo >&2 "[pre-push] E2E tests failed, see output above."
+	exit 1
 fi
 echo "$PREFIX All E2E tests passed!"
 
@@ -107,16 +107,16 @@ echo "$PREFIX Running IAM integration tests..."
 cd "$DIR/api/pkg/apps/iam" || exit
 export GO111MODULE=on
 if ! go test; then
-  echo >&2 "[pre-push] Integration tests failed, see output above."
-  exit 1
+	echo >&2 "[pre-push] Integration tests failed, see output above."
+	exit 1
 fi
 
 echo "$PREFIX Running CMS integration tests..."
 
 cd "$DIR/api/pkg/apps/cms" || exit
 if ! go test; then
-  echo >&2 "[pre-push] Integration tests failed, see output above."
-  exit 1
+	echo >&2 "[pre-push] Integration tests failed, see output above."
+	exit 1
 fi
 
 exit 0
